name: pypi-publish
on:
  push:
    tags:
      - "*"
jobs:
  pypi-publish:
    name: pypi-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Use python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
      - name: Update versions of packages
        run: poetry version $GITHUB_REF_SLUG
      - name: Build Python modules
        run: make build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.DIMAKIS_TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/